#markdown: rdiscount
permalink: /:title/
url: http://xiaofa307.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: 小法
description: ！
author: xiaofa307
email: g80you@gmail.com
safe: false
about: ""
